### ISSUE TITLE
Define Craft CMS Version

### ISSUE THREAD

**Issue by christophstockinger** [urbantrout/craftcms#14]
Hi
Is it possible to define the Craft CMS version?

Currently, version 3.15. or similar is installed when I run the script.

But Craft CMS is meanwhile in the version >= 3.4.4.1.

So I want to define in the script which Craft version should be installed.

**Comment by urbantrout** [comment]
Just add `craftcms/cms:^3.4.0` to you `DEPENDENCIES` in the `docker-compose.yml`
