### ISSUE TITLE
last saved db backup sql is not loading 

### ISSUE THREAD

**Issue by marvinpyles** [urbantrout/craftcms#5]
After I remove the sql entry inside .ignore, I would expect the last saved craft db backup sql to load. However, this is not the case. Docker appears to still be pulling up the last sql backup named "craft-cms-installation*.sql" instead of my last saved sql backup: "site-name*.sql".  

I even tried to rename my last named backup using the same conventions as the one docker is importing.. No cigar. Still does not work.

**Comment by urbantrout** [comment]
The script responsible for importing the DB dump should actually use only the latest sql file in the backups folder (sorted by mtime). I tried reproducing your problem without any success. Are you sure you are using the latest docker image? Try updating it with `docker pull urbantrout/craftcms`, `docker pull urbantrout/craftcms:mysql` or `docker pull urbantrout/craftcms:postgresql`

**Comment by pddew** [comment]
I have this problem too after using Ryan Irelan's fork of this repo; I have also changed the site name from the CP.

I've included more detail here:
https://craftcms.stackexchange.com/q/28682/8833

**Comment by urbantrout** [comment]
I am pretty busy right now, but I will take a look at it on the weekend…

**Comment by pddew** [comment]
No rush at all - I realised I could remove all backups except for the one I want, then the import works ok.

I think this might be to do with a name change, which prevents backups going into .ignore.
Thanks

**Comment by urbantrout** [comment]
Yeah. I always delete all but the most recent one ;)

**Comment by urbantrout** [comment]
Are you sure you are using the latest docker image? You can update the image with `docker pull urbantrout/craftcms:<tag>`

I just checked and my image is using the most recent backup when spinning up the containers.

**Comment by urbantrout** [comment]
@pddew Are you sure you are using the latest docker image? You can update the image with docker pull urbantrout/craftcms:<tag>

I just checked and my image is using the most recent backup when spinning up the containers.

**Comment by urbantrout** [comment]
I'm closing this issue because it has been inactive for a few months.
