### ISSUE TITLE
Question on file premissions , when saving assets.

### ISSUE THREAD

**Issue by bomanden** [urbantrout/craftcms#6]
This ,maybe a 'docker on windows' problem:  
But I'm unable to save assets on a volume defined in assets './web/assets/images/uploads/'

Getting this error in crafts  cp: 
Upload failed. The error message was: “Impossible to create the root directory "/web/assets/images/uploads". mkdir(): Permission denied”

**Comment by bomanden** [comment]
was a path issue, you can delete my post, works great

**Comment by brianyuen** [comment]
@bomanden Having the same issues with Docker in Ubuntu. You said it was a path issue, but can you be a little more specific? Thanks!

**EDIT**: I seemed to have found the answer. To those looking for the correct path, add this line: `die($_SERVER['DOCUMENT_ROOT']);` to the index.php in the 'web' directory temporarily. Now when you visit your site, the correct path will get printed somewhere on the page. For me, it was `/var/www/htdocs/web/uploads`

**Comment by henrypenny** [comment]
I'm getting the error on Envoyer.
Craft is complaining that it can't create the root folder. But the folder already exists and is completely writable.

```
Upload failed. The error message was: “Impossible to create the root directory 

"/home/websitedev/container/application/web/assets". mkdir(): Permission denied”

$ ll /home/websitedev/container/application/web/assets
total 8
drwxrwxrwx 2 websitedev websitedev 4096 Jan 29 16:28 ./
drwx------ 3 websitedev websitedev 4096 Jan 29 16:28 ../
```

**Comment by henrypenny** [comment]
Sorry - this looks like I fork...
