### ISSUE TITLE
 failed to install XXXXX: No plugin exists with the handle "XXXXXX".

### ISSUE THREAD

**Issue by ipetrov87** [urbantrout/craftcms#7]
HI I have a issue in at the step when plugins are installing.  I got this messages

```
 ==> ✅  All dependencies successfully installed.
 ==> Activating Plugins.
*** installing imager
*** failed to install imager: No plugin exists with the handle "imager".
```

If i remove all plugins all runs, but with plugins not.

I am using Docker on  Windows 10

**Comment by urbantrout** [comment]
Can you please provide your docker-compose config?

**Comment by ipetrov87** [comment]
It is fixed. I think it was because I was not provide the correct database dump. You done great work!

**Comment by urbantrout** [comment]
Sometimes this has to do with file permissions. Make sure `project.yml` is writable by the server…
