### ISSUE TITLE
TypeError: Return value of craft\web\Application::getIsLive() must be of the type boolean, null returned

### ISSUE THREAD

**Issue by matt3s** [urbantrout/craftcms#9]
The error is coming after a fresh setup (the mysql version) with 'docker-compose up' and visit the localhost with a craft database update with the browser.

**Comment by matt3s** [comment]
--> This workaround works: 
 adding 'isSystemLive' => true in general.php

**Comment by urbantrout** [comment]
See https://craftcms.stackexchange.com/a/29533
